### ISSUE TITLE
Create many folders cause force close

### ISSUE THREAD

**Issue by liemlyquan** [AnuraxSharma1512/File_Quest#12]
Create many folder continuously cause the program to force close

<h1>Step to re-create</h1>

<ol>
<li>Press “New”</li>
<li>Press “Create folder”</li>
<li>Enter folder name and press check mark</li>
<li>Press “Create folder”</li>
<li>Enter folder name and press check mark</li>
</ul>
<h1>Result</h1>
Program force close

<h1>Run in</h1>
Samsung Galaxy Note 4, stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
this problem is solved....
