### ISSUE TITLE
App freeze after switch between panels continuosly

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#16]
Cut a folder and paste it to the same directory as before cause the folder to be deleted.

# Step to re-create:
Switch between "File gallery" and "/" continuously

# Result:
After a set amount of switching, the app freeze.

# Note:
This only work on the real device with spec below, other devices cannot re-create this issue.

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
there's no fault in my app its because of airpush 360 ads and ads will be removed before the update....
