### ISSUE TITLE
"Multi-sel" mode does not display correctly

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#17]
Cut a folder and paste it to the same directory as before cause the folder to be deleted.

# Step to re-create:
1. Press “Multi-sel”
2. Press “Enable multi select for Your app store”
3. Restart the problem
4. Go to “Your app store” tab

# Result:
The multi-sel mode is enabled, but does not display correctly

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
Multi select mode is in lollipop style now.
