### ISSUE TITLE
Open image using default viewer not work

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#18]
Unable to open image using Android default image viewer.

# Step to re-create:
1. Press an image
2. Choose open using “Gallery” (Android default image viewer)

# Result:
Error “Unable to find item”

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by Drawnzer** [comment]
It can't load HD images in image view.
Needs to be fixed for HD images.

**Comment by AnuraxSharma1512** [comment]
now image viewer opens HD images also...

I have tested with a image 3840x2160p.
