### ISSUE TITLE
Delete image by "FQ Image Viewer" is not remove from the list imediately

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#19]
Image deleted by "FQ Image Viewer" still show on the list view.

# Step to re-create:
1. Press an image
2. Choose open using “FQ Image Viewer”
3. Press “Delete”

# Result:
File deleted, but still shown on the list

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by Drawnzer** [comment]
in the recent i\update its not working....

**Comment by AnuraxSharma1512** [comment]
now it updates the list view after the image is deleted from image viewer class....
