### ISSUE TITLE
Crash when create hidden folder manually

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#2]
When create a normal folder WITH dot (".") at the beginning, the app crash.

# Step to re-create:
1. Press "New"
2. Press "Create folder"
3. Enter any name for the folder **WITH** dot (".") **BEFORE** the name.
4. Press "OK"

# Result:
The app crash but the folder (hidden) is created.

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
this issue has been solved in some earlier commit by me.
