### ISSUE TITLE
Crash when create hidden file manually without extension

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#3]
When create a normal folder WITH dot (".") at the beginning, the app crash.

# Step to re-create:
1. Press "New"
2. Press "Create empty file"
3. Enter any name for the folder **WITH** dot (".") **BEFORE** the name **WITHOUT** file extension.
4. Press "Benchmark"

# Result:
The app crash and nothing is created.

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
already fixed in earlier commit by me.
