### ISSUE TITLE
"Delete files after zipping" crash in "Multi-sel" mode

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#5]
Zipping a folder and chose to delete files after zipping when the app is in multi-sel mode cause the app to crash, the folder is deleted, the archive file is created but there nothing in it.

# Step to re-create:
1. Press “Multi-sel”
2. Press “Enable multi selection for SD card”
3. Select a folder
4. Press “Zip”
5. Select “Delete files after zipping
6. Press “Start”

# Result:
* The app crash
* The original folder is deleted
* An empty archive is created

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
Fixed.
