### ISSUE TITLE
Create zip file using context menu not working correctly with delete files after zipping

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#6]
Zipping a folder and chose to delete files after zipping using the context menu (long press on a folder) create an corrupted archive and delete the original folder

# Step to re-create:
1. Long press a folder
2. Press “Create archive”
3. Select “Delete files after zipping"
4. Press “Start”

# Result:
* The original folder is deleted
* An corrupted archive is created

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by AnuraxSharma1512** [comment]
Fixed.
