### ISSUE TITLE
Create zip file using context menu not working correctly with keep files after zipping

### ISSUE THREAD

**Issue by hungly** [AnuraxSharma1512/File_Quest#8]
Zipping a folder and chose to delete files after zipping using the context menu (long press on a folder) create an corrupted archive and delete the original folder

# Step to re-create:
1. Long press a folder
2. Press “Create archive”
3. Select “Keep files after zipping"
4. Press “Start”

# Result:
* An corrupted archive is created

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by Drawnzer** [comment]
there's a bug in my algorithm for creating zip files.
I will fix it soon.

**Comment by AnuraxSharma1512** [comment]
Fixed
